name: flutter_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  google_sign_in: ^7.2.0
  google_fonts:
  freezed_annotation: ^2.4.4
  percent_indicator:
  go_router:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.1
  firebase_auth: ^6.1.4
  flutter_flavor: ^3.1.4
  flutter_flavorizr: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.11
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/google_fonts/

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
  flavors:
    dev:
      app:
        name: "テキストSNS Dev"
      android:
        applicationId: "com.firebaseapp.naruto_be91a"
      ios:
        bundleId: "com.firebaseapp.narutoBe91a"
    prod:
      app:
        name: "テキストSNS"
      android:
        applicationId: "com.firebaseapp.naruto_sns_prod"
      ios:
        bundleId: "com.firebaseapp.narutoSnsProd"
